---
config:
  layout: elk
---
flowchart TB
    Centro(("Referências para licitações e <br>contratos administrativo<br>Lei nº 14.133/2021")) --> DE["Despensa Eletrônica"] & TR["Termo de Referência Digital"] & ETP["Estudo Técnico Preliminar Digital"] & PP["Pesquisa de Preços"] & EC["Entes de Contratação"] & Cred["Credenciamento"] & Gov["Governança nas Contratações"] & PGC["Planejamento e Gestão de Contratos (PGC)"] & SRP["Sistema de Registro de Preços (SRP)"] & MenorPreco["Modalidade de Licitação: Menor Preço"] & Alcadas["Análise de alçadas"]
    Centro -- "<span style=background-color:>Soluções de TIC</span>" --> TIC@{ label: "<span style=\"color:\">Instrução Normativa SGD/ME nº 94/2022</span>" }
    DE --> IN67{{"IN SEGES/ME n° <b>67</b>/2021"}}
    TR --> IN81{{"IN SEGES/ME n° <b>81</b>/2022"}}
    ETP --> IN58{{"IN SEGES/ME n°<b> 58</b>/2022"}}
    PP --> IN65{{"IN SEGES/ME n° <b>65</b>/2021"}}
    EC --> D11246{{"Decreto nº <b>11.246</b>/2022"}}
    Cred --> D11246
    Gov --> D10193{{"Decreto nº <b>10.193</b>/2019"}} & P8678{{"Portaria SEGES/ME nº <b>8.678</b>/2021"}}
    TIC --> P938{{"Portaria SEGES/ME nº 938/2022"}} & P2715{{"Portaria SGD/MGI nº 2.715/2023"}} & P5950{{"Portaria SGD/MGI nº 5.950/2023"}} & P1070{{"Portaria SGD/MGI nº 1.070/2023"}} & P750{{"Portaria SGD/MGI nº 750/2023"}} & P370{{"Portaria SGD/MGI nº 370/2023"}}
    P938 --> pmctic["Normas específicas para uso de <b>catálogo Eletrônico</b>"]
    P2715 --> computador["Normas para a contratações de <b>Estações de Trabalho</b>"]
    P5950 --> nuvem["Normas para a contratações de<b> Serviços de Nuvem</b>"]
    P1070 --> operacaoinfra["Normas para a contratações de serviços de<b> operação de infraestrutura e atendimento a usuários de TIC</b>"] & n6@{ label: "<span style=\"padding-left:\">Portarias <b>SGD/MGI nº 5.921 / 2026</b>; nº 6.055 / 2025; nº 6.680 / 2024;</span>" }
    P750 --> dev["Normas para a contratações no <b>desenvolvimento de software</b>"] & metricas["Portarias <b>SGD/MGI nº 3.656 / 2026,</b> instituiu o Roteiro de Métricas no desenvolvimento de Sotware do SISP"]
    P370 --> impressao["Normas para a contratação de <b>Serviços de Outsourcing de Impressão</b>"]
    PGC --> D109472022{{"Decreto nº<b> 10.947</b>/2022"}}
    SRP --> D114622023{{"Decreto nº <b>11.462</b>/2023"}}
    MenorPreco --> D732022{{"IN SEGES/ME n° <b>73</b>/2022"}}
    Alcadas --> IN6{{"IN SGD/MGI n°<b> 6</b>/2023"}}

    click TIC "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/processo-de-contratacao-de-solucoes-de-tic-regido-pela-lei-ndeg-14-133-de-2021"
    click P938 "https://www.gov.br/transferegov/pt-br/legislacao/portarias/portaria-seges-me-no-938-de-2-de-fevereiro-de-2022"
    click P2715 "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/modelo-de-contratacao-e-gestao-de-estacoes-de-trabalho"
    click P5950 "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/modelo-de-contratacao-de-software-e-servicos-em-nuvem"
    click P1070 "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/modelo-de-contracao-de-servicos-de-operacao-de-infraestrutura-e-de-atendimento-a-usuarios-de-tic"
    click P750 "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/modelo-de-contratacao-de-servicos-de-desenvolvimento-manutencao-e-sustentacao-de-software"
    click P370 "https://www.gov.br/governodigital/pt-br/contratacoes-de-tic/legislacao/modelo-de-contratacao-de-servicos-de-outsourcing-de-impressao"
    click n6 "https://www.in.gov.br/web/dou/-/portaria-sgd/mgi-n-5.921-de-22-de-julho-de-2026-721095205"
